# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QTAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('ACC', 'Account data'), ('MKT', 'Market data'), ('ODR', 'Orders placement')], max_length=3)),
                ('access_token', models.CharField(max_length=32)),
                ('token_type', models.CharField(max_length=32)),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=32)),
                ('api_server', models.URLField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
