# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabla_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtaccess',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qtaccess',
            name='scope',
            field=models.CharField(choices=[('ACC', 'Account data'), ('MKT', 'Market data'), ('ODR', 'Order placement')], max_length=3),
        ),
    ]
