# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nabla_core', '0003_auto_20171031_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtaccess',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qtaccess',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
