# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nabla_core', '0004_auto_20171103_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('status', models.CharField(max_length=64)),
                ('primary', models.BooleanField()),
                ('client_account_type', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
