# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nabla_core', '0005_qtaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateTimeField()),
                ('transaction_date', models.DateTimeField()),
                ('settlement_date', models.DateTimeField()),
                ('action', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=64)),
                ('symbol_id', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('currency', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('commission', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
