# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabla_core', '0006_qtactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtactivity',
            name='symbol_id',
            field=models.IntegerField(),
        ),
    ]
