# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nabla_core', '0007_auto_20171106_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('cash', models.FloatField()),
                ('market_value', models.FloatField()),
                ('total_equity', models.FloatField()),
                ('buying_power', models.FloatField()),
                ('qt_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nabla_core.QTAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
